/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_home (void);
GtkWidget* create_employee (void);
GtkWidget* create_admin (void);
GtkWidget* create_espace_capteur (void);
GtkWidget* create_gestion_capteur (void);
GtkWidget* create_ajouter_capteur (void);
GtkWidget* create_modifier_capteur (void);
GtkWidget* create_supprimer_capteur (void);
GtkWidget* create_enregistrement (void);
GtkWidget* create_ajouter_enregistrement (void);
GtkWidget* create_alarmante (void);
GtkWidget* create_marque_def (void);
GtkWidget* create_Gestion_des_clients (void);
GtkWidget* create_ajouter_clients (void);
GtkWidget* create_modifier_clients (void);
GtkWidget* create_supprimer_clients (void);
GtkWidget* create_Gestion_des_employes (void);
GtkWidget* create_modifier_employes (void);
GtkWidget* create_ajouter_employes (void);
GtkWidget* create_supprimer_employes (void);
GtkWidget* create_gestiondeplantation (void);
GtkWidget* create_Ajouter_plante (void);
GtkWidget* create_Modifier_plante (void);
GtkWidget* create_Supprimer_plante (void);
GtkWidget* create_gestion_annee_la_plus_seche (void);
GtkWidget* create_ajouter_annees (void);
GtkWidget* create_supprimer_annees (void);
